apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: attendance
  namespace: api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: attendance
    spec:
      containers:
        - name: attendance
          image: crdschurch/crds-attendance:${DOCKER_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: NODE_ENV
              value: "prod"
            - name: DB_HOST
              value: "${AT_DB_HOST}"
            - name: DB_NAME
              value: "${AT_DB_NAME}"
            - name: DB_USER
              value: "${AT_DB_USER}"
            - name: DB_PASS
              value: "${AT_DB_PASS}"
            - name: TABLE_PREFIX_USER
              value: "${TABLE_PREFIX_USER}"
            - name: TABLE_PREFIX_SITE
              value: "${TABLE_PREFIX_SITE}"
            - name: TABLE_PREFIX_SERVICE
              value: "${TABLE_PREFIX_SERVICE}"
            - name: TABLE_PREFIX_MINISTRY
              value: "${TABLE_PREFIX_MINISTRY}"
            - name: TABLE_PREFIX_ENTRY_TYPE
              value: "${TABLE_PREFIX_ENTRY_TYPE}"
            - name: TABLE_PREFIX_SERVICE_INSTANCE
              value: "${TABLE_PREFIX_SERVICE_INSTANCE}"
            - name: TABLE_PREFIX_REPORT_HASH
              value: "${TABLE_PREFIX_REPORT_HASH}"
            - name: CRDS_API_KEY
              value: "${CRDS_API_KEY}"
            - name: CONFIG_SESSION_SECRET
              value: "${CONFIG_SESSION_SECRET}"
            - name: CONFIG_AUTH_URL
              value: "${CONFIG_AUTH_URL}"
            - name: CONFIG_SENDGRID_API_KEY
              value: "${CONFIG_SENDGRID_API_KEY}"
            - name: CONFIG_SENDGRID_FROM_EMAIL
              value: "${CONFIG_SENDGRID_FROM_EMAIL}"
            - name: CONFIG_DOMAIN_NAME
              value: "${CONFIG_DOMAIN_NAME}"