apiVersion: v1
kind: Service
metadata:
  name: attendance-service
  namespace: api
  labels:
    app: attendance-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: attendance