version: '3'
services:
  attendance:
    image: crdschurch/crds-attendance:${DOCKER_TAG:-development}
    build:
      args:
        - DEPLOYMENT_PATH
      context: ../../
      dockerfile: ./deployment/docker/prod.Dockerfile
    container_name: crds-attendance
    ports:
      - 80:8000